# Generated by Django 3.1.5 on 2021-01-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
    ]
